name: Version Bump and Tag

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump-and-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Determine Bump Type Based on Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" == "release"* ]]; then
            echo "BUMP_TYPE=minor" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "hotfix"* ]]; then
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "bump"* ]]; then
            echo "BUMP_TYPE=major" >> $GITHUB_ENV
          else
            echo "BUMP_TYPE=none" >> $GITHUB_ENV
          fi

      - name: Bump version
        if: steps.bump-type.outputs.type != 'none'
        id: bump-version
        run: |
          VERSION=$(python bump_version.py --file_path apps/app/build.gradle --type $BUMP_TYPE)
          echo "New version: $VERSION"
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Commit and Tag
        if: env.NEW_VERSION
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add apps/app/build.gradle
          git commit -m "Bump version to $NEW_VERSION"
          git tag -a $NEW_VERSION -m "Version $NEW_VERSION"
          git push origin $NEW_VERSION
          git push origin main
