name: Version Bump and Tag

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump-and-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Determine Bump Type Based on Branch Name
        id: bump-type
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" == "release"* ]]; then
            echo "::set-output name=type::minor"
          elif [[ "$BRANCH_NAME" == "hotfix"* ]]; then
            echo "::set-output name=type::patch"
          elif [[ "$BRANCH_NAME" == "bump"* ]]; then
            echo "::set-output name=type::major"
          else
            echo "::set-output name=type::none"
          fi

      - name: Bump version
        if: steps.bump-type.outputs.type != 'none'
        id: bump-version
        run: |
          VERSION=$(python bump_version.py --file_path path/to/your/file.json --type ${{ steps.bump-type.outputs.type }})
          echo "::set-output name=version::$VERSION"
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit and Tag
        if: env.NEW_VERSION
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add path/to/your/file.json
          git commit -m "Bump version to $NEW_VERSION"
          git tag $NEW_VERSION
          git push
          git push --tags
